# https://yazi-rs.github.io/docs/configuration/theme

[icon]
globs = [
	{ name = "**/LICENSE-*",          text = "Â©ï¸" },
]
dirs = []
files = [
	{ name = "Makefile",              text = "âš’ï¸" },
	{ name = "makefile",              text = "âš’ï¸" },
	{ name = "GNUmakefile",           text = "âš’ï¸" },
	{ name = "CMakeLists.txt",        text = "âš’ï¸" },
	{ name = "justfile",              text = "âš’ï¸" },
	{ name = "Dockerfile",            text = "ğŸ‹" },
	{ name = "Cargo.lock",            text = "ğŸ¦€" },
	{ name = "Cargo.toml",            text = "ğŸ¦€" },
	{ name = "clippy.toml",           text = "ğŸ¦€" },
	{ name = "rustfmt.toml",          text = "ğŸ¦€" },
	{ name = "requirements.txt",      text = "ğŸ" },

	# Files recognized by GitHub (https://gist.github.com/jakebrinkmann/c63eaedbe384516e4a7bc133c1e1066b)
	{ name = "README",                text = "ğŸ“" },
	{ name = "LICENSE",               text = "Â©ï¸" },
	{ name = "CHANGELOG",             text = "ğŸ“" },
	{ name = "CONTRIBUTING",          text = "ğŸ“" },
	{ name = "SUPPORT",               text = "ğŸ“" },
	{ name = "CONTRIBUTORS",          text = "ğŸ“" },
	{ name = "AUTHORS",               text = "ğŸ“" },
	{ name = "ACKNOWLEDGEMENTS",      text = "ğŸ“" },
	{ name = "ISSUE_TEMPLATE",        text = "ğŸ“" },
	{ name = "PULL_REQUEST_TEMPLATE", text = "ğŸ“" },
	{ name = "CODEOWNERS",            text = "ğŸ“" },
	{ name = "OWNERS",                text = "ğŸ“" },
	{ name = "COPYING",               text = "ğŸ“" },
]
exts = [
	# Documents
	{ name = "txt",         text = "ğŸ“" },
	{ name = "md",          text = "ğŸ“" },
	{ name = "MD",          text = "ğŸ“" },
	{ name = "journal",     text = "ğŸ§¾" },
	{ name = "ldg",         text = "ğŸ§¾" },
	{ name = "bib",         text = "ğŸ“œ" },
	{ name = "pdf",         text = "ğŸ“š" },
	{ name = "djvu",        text = "ğŸ“š" },
	{ name = "epub",        text = "ğŸ“š" },
	{ name = "srt",         text = "ğŸ“œ" },
	{ name = "vtt",         text = "ğŸ“œ" },

	# Images
	{ name = "png",         text = "ğŸ–¼ " },
	{ name = "gif",         text = "ğŸ–¼ " },
	{ name = "ico",         text = "ğŸ–¼ " },
	{ name = "svg",         text = "ğŸ§¬" },
	{ name = "eps",         text = "ğŸ§¬" },
	{ name = "jpg",         text = "ğŸ“¸" },
	{ name = "jpeg",        text = "ğŸ“¸" },

	# Audio
	{ name = "wav",         text = "ğŸµ" },
	{ name = "mp3",         text = "ğŸµ" },
	{ name = "opus",        text = "ğŸµ" },
	{ name = "ogg",         text = "ğŸµ" },
	{ name = "m4a",         text = "ğŸµ" },
	{ name = "flac",        text = "ğŸµ" },

	# Video
	{ name = "mp4",         text = "ğŸ¥" },
	{ name = "mkv",         text = "ğŸ¥" },
	{ name = "webm",        text = "ğŸ¥" },
	{ name = "mpeg",        text = "ğŸ¥" },
	{ name = "mpg",         text = "ğŸ¥" },
	{ name = "avi",         text = "ğŸ¥" },
	{ name = "mov",         text = "ğŸ¥" },
	{ name = "wmv",         text = "ğŸ¥" },
	{ name = "asf",         text = "ğŸ¥" },
	{ name = "flv",         text = "ğŸ¥" },
	{ name = "m4v",         text = "ğŸ¥" },
	{ name = "qt",          text = "ğŸ¥" },
	{ name = "3gp",         text = "ğŸ¥" },

	# Project files
	{ name = "xcf",         text = "ğŸ¨" },
	{ name = "kra",         text = "ğŸ¨" },
	{ name = "ase",         text = "ğŸ‘»" },
	{ name = "aseprite",    text = "ğŸ‘»" },
	{ name = "ods",         text = "ğŸ“Š" },
	{ name = "xls",         text = "ğŸ“Š" },
	{ name = "xlsx",        text = "ğŸ“Š" },
	{ name = "ardour",      text = "â›º" },
	{ name = "ove",         text = "ğŸ«’" },
	{ name = "h2song",      text = "ğŸ¥" },
	{ name = "ipynb",       text = "ğŸ“—" },

	# Source code
	{ name = "css",         text = "ğŸ¨" },
	{ name = "html",        text = "ğŸŒ" },
	{ name = "zig",         text = "âš¡" },
	{ name = "rs",          text = "ğŸ¦€" },
	{ name = "py",          text = "ğŸ" },
	{ name = "nix",         text = "â„ï¸" },
	{ name = "patch",       text = "ğŸ©¹" },
	{ name = "lua",         text = "ğŸ§¿" },

	# Binary
	{ name = "bin",         text = "â¬›" },
	{ name = "dat",         text = "â¬›" },
	{ name = "so",          text = "ğŸ§°" },
	{ name = "a",           text = "ğŸ§°" },
	{ name = "o",           text = "â—¼ï¸" },

	# Configuration / serialization
	{ name = "conf",        text = "âš™ï¸" },
	{ name = "config",      text = "âš™ï¸" },
	{ name = "xml",         text = "âš™ï¸" },
	{ name = "toml",        text = "âš™ï¸" },
	{ name = "yaml",        text = "âš™ï¸" },
	{ name = "ini",         text = "âš™ï¸" },
	{ name = "csv",         text = "âš™ï¸" },
	{ name = "json",        text = "âš™ï¸" },

	# Documentation
	{ name = "1",           text = "â„¹ï¸" },
	{ name = "2",           text = "â„¹ï¸" },
	{ name = "3",           text = "â„¹ï¸" },
	{ name = "4",           text = "â„¹ï¸" },
	{ name = "5",           text = "â„¹ï¸" },
	{ name = "6",           text = "â„¹ï¸" },
	{ name = "7",           text = "â„¹ï¸" },
	{ name = "8",           text = "â„¹ï¸" },
	{ name = "9",           text = "â„¹ï¸" },
	{ name = "nfo",         text = "â„¹ï¸" },
	{ name = "info",        text = "â„¹ï¸" },

	# Archives / packages / databases
	{ name = "zip",         text = "ğŸ“¦" },
	{ name = "rar",         text = "ğŸ“¦" },
	{ name = "7z",          text = "ğŸ“¦" },
	{ name = "gz",          text = "ğŸ“¦" },
	{ name = "bz",          text = "ğŸ“¦" },
	{ name = "xz",          text = "ğŸ“¦" },
	{ name = "deb",         text = "ğŸ“¦" },
	{ name = "jar",         text = "ğŸ“¦" },
	{ name = "pak",         text = "ğŸ“¦" },
	{ name = "ispm",        text = "ğŸ“¦" },
	{ name = "iso",         text = "ğŸ“€" },
	{ name = "img",         text = "ğŸ“€" },
	{ name = "db",          text = "ğŸ—ƒï¸" },
	{ name = "db3",         text = "ğŸ—ƒï¸" },
	{ name = "sqlite",      text = "ğŸ—ƒï¸" },
	{ name = "sqlite3",     text = "ğŸ—ƒï¸" },

	# Misc
	{ name = "bak",         text = "ğŸ—„ï¸" },
	{ name = "gpg",         text = "ğŸ”’" },
	{ name = "asc",         text = "ğŸ”’" },
	{ name = "pub",         text = "ğŸ”‘" },
	{ name = "sig",         text = "ğŸªª" },
	{ name = "torrent",     text = "ğŸ”½" },
	{ name = "part",        text = "ğŸ’”" },
	{ name = "ninja",       text = "âš’ï¸" },
	{ name = "trashinfo",   text = "ğŸ—‘ï¸" },
]
conds = [
	{ if = "orphan",        text = "âŒ" },
	{ if = "char",          text = "ğŸ–±ï¸" },
	{ if = "block",         text = "ğŸ’½" },
	{ if = "fifo",          text = "â¡ï¸" },
	{ if = "sock",          text = "â†”ï¸" },
	{ if = "sticky",        text = "ğŸ¤" },
	#{ if = "link",          text = "ğŸ“" },
	{ if = "dummy",         text = "â“" },

	{ if = "dir",           text = "ğŸ“" },
	{ if = "exec",          text = "ğŸ‘¾" },
	{ if = "!dir",          text = "ğŸ“ƒ" },
]
